### ISSUE TITLE
Add category Jobs & Internships

### ISSUE THREAD

**Issue by palash25** [sdmg15/Best-websites-a-programmer-should-visit#268]
I would like to work on this

**Comment by lalitmee** [comment]
@sdmg15 Hey, I don't know what the problem is. But there is some problem with **Travis build**. When I added first-time Paysa. Url was this: **https://www.paysa.com/**. Then I got an error in the pull request. Then I read the details of the Travis build and I found out that trailing slash is creating the problem. So I removed that.

But when I created another pull request, it was showing error in the pull request with the link of Paysa(Url was this: https://www.paysa.com). And it was also showing error with the other link.

Please look into this. Every time I create a pull request it creates a lot of difficulty for me.

**Comment by sdmg15** [comment]
Hello,
Alright when you make a PR, if you can't resolve the build error 
Just leave I'll do it .
Thanks.

**Comment by lalitmee** [comment]
Ok, but I will also try to resolve the build error. If I can't then I will leave that to you. Thanx
